// Question 23: Conditional Tests: Write a series of conditional tests. Predict the results of each test.
var namee = "Alishba";
console.log("Is Name == 'alishba'? I Predict True Otherwise I Predict False");
console.log(namee === "Alishba");
console.log(namee === "alish");
var age = 18;
console.log("Is age == 18 ? I Predict True Otherwise I Predict False");
console.log(age === 18);
console.log(age === 6);
var Class = "10th";
console.log("Is Class == '10th'? I Predict True Otherwise I Predict False");
console.log(Class === "10th");
console.log(Class === "4");
var city = "hyderabad";
console.log("Is city == 'hyderabad'? I Predict True Otherwise I Predict False");
console.log(city === "hyderabad");
console.log(city === "karachi");
var school = "army public";
console.log("Is School == 'army public'? I Predict True Otherwise I Predict False");
console.log(school === "army public");
console.log(school === "true educator");
export {};
